archive/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^results/$', views.search_results, name='results'),
    url(r'^contact-us/$', views.contact, name='contact'),
    url(r'^history/$', views.history, name='history'),
    url(r'^mission/$', views.mission, name='mission'),
    url(r'^media/$', views.media, name='media'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^verify/$', views.verify_upload, name='verify_upload'),
    url(r'^categories/$', views.categories, name='categories'),
]

blog/urls.py
from django.conf.urls import url

from . import views

#urlpatterns = [
#    url(r'^articles/', views.articles, name='articles')
#    url(r'^articles/(?P<num>[0-9]+)/$', views.article, name='article')
#]

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<article_id>[0-9]+)/$', views.article, name='article'),
]

rsvp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import authenticate

urlpatterns = [
    # Examples:
    # url(r'^$', 'rsvp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^$', 'rsvp.views.home', name='home'),
    url(r'^', include('archive.urls', namespace="archive")),
    url(r'^articles/', include('blog.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url('^', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

archive/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model):
    keyword = models.CharField(max_length=255)

    def __str__(self):
        return self.keyword

class Category(models.Model):
    category = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category

class Document(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, blank=True)
    publication = models.CharField(max_length=255, blank=True)
    publication_date = models.CharField(max_length=255, blank=True)
    file = models.FileField(max_length=255, upload_to='documents/%Y/%m/%d/')
    keywords = models.ManyToManyField(Keyword)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.title

archive/views.py
'''Views for RSVP America'''
import os
import pickle
from smtplib import SMTPException

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import EmailMessage, send_mail

from .whoosh_search import Index
from archive.models import Document
from archive.ocrPdf import Converter
from blog.models import Article
from rsvp.settings import MEDIA_ROOT, MEDIA_URL
from django.contrib import messages

import sys

def home(request):
    '''Render the homepage.'''
    article_list = Article.objects.order_by('id')[:3]
    context = {'status': None, 'article_list': article_list}
    if request.GET.__contains__('status'):
        context['status'] = request.GET.get('status')

    return render(request, 'archive/home.html', context)

def categories(request):
    '''Render the categories page.'''
    return render(request, 'archive/categories.html')

def history(request):
    '''Render the history page.'''
    return render(request, 'archive/history.html')

def mission(request):
    '''Render the mission page.'''
    return render(request, 'archive/mission.html')

def media(request):
    '''Render the media page.'''
    return render(request, 'archive/media.html')

def search_results(request):
    '''Parse a user query, and return a paginated list of results.'''
    if request.GET.__contains__('q'):
        query = request.GET.get('q')
        fulltext = request.GET.get('fulltext')

        temp_index = Index('indexdir')
        full_results = temp_index.search(query.lower(), fulltext)
        paginator = Paginator(full_results, 12) # Show 12 results per page

        page = request.GET.get('page')
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver the first page
            page = 1
            results = paginator.page(page)
        except EmptyPage:
            # If page is out of range, deliver the last page of results
            page = paginator.num_pages
            results = paginator.page(page)

        first_doc = int(page) * 12 - 11
        last_doc = int(page) * 12
        if last_doc > int(paginator.count):
            last_doc = paginator.count

        if int(page) - 3 < 0:
            page_range = paginator.page_range[0:5]
        else:
            page_range = paginator.page_range[int(page)-3:int(page)+2]

        context = {
            'query':     request.GET.get('q'),
            'results':   results,
            'total':     paginator.count,
            'page_range': page_range,
            'first_doc': first_doc,
            'last_doc':  last_doc,
            'full_text': fulltext
        }
        return render(request, 'archive/search_results.html', context)
    elif request.GET.__contains__('cat'):
        category = request.GET.get('cat')

        temp_index = Index('indexdir')
        full_results = temp_index.cat_search(category)
        paginator = Paginator(full_results, 12) # Show 12 results per page

        page = request.GET.get('page')
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver the first page
            page = 1
            results = paginator.page(page)
        except EmptyPage:
            # If page is out of range, deliver the last page of results
            page = paginator.num_pages
            results = paginator.page(page)

        first_doc = int(page) * 12 - 11
        last_doc = int(page) * 12
        if last_doc > int(paginator.count):
            last_doc = paginator.count

        if int(page) - 3 < 0:
            page_range = paginator.page_range[0:5]
        else:
            page_range = paginator.page_range[int(page)-3:int(page)+2]

        context = {
            'cat':     request.GET.get('cat'),
            'results':   results,
            'total':     paginator.count,
            'page_range': page_range,
            'first_doc': first_doc,
            'last_doc':  last_doc
        }
        return render(request, 'archive/search_results.html', context)
    else:
        return HttpResponseRedirect('/')

def contact(request):
    '''Send user message to FPP, redirect to / with success message or
    complain on failure.'''
    if request.method == 'POST':
        subject = '[RSVP America] Message from %s' % request.POST['name']
        body = 'From:\n{0}\n{1}\n\nMessage:\n{2}'.format(
            request.POST['name'],
            request.POST['email'],
            request.POST['comments']
        )
        from_email = request.POST['email']
        recipient_list = ['bigideamgroup@gmail.com']
        try:
            send_mail(subject,
                      body,
                      from_email,
                      recipient_list,
                      fail_silently=True)
            messages.add_message(request, messages.SUCCESS, 'Message Sucessfully Sent!')
            return HttpResponseRedirect('/')
        except SMTPException:
            messages.add_message(request, messages.ERROR, 'Message Failed To Send!')
            return HttpResponseRedirect('/')
    return HttpResponseRedirect('/')

def upload(request):
    '''Send user-contributed file to FPP, redirect to / with success message
    or complain on failure.'''
    if request.method == 'POST':
        subject = '[RSVP America] User Contribution'
        body = 'An RSVP America user submitted the attached file.'
        from_email = 'will@quexxon.net'
        recipient_list = ['bigideamgroup@gmail.com']
        attach = request.FILES['upload']
        email = EmailMessage(subject, body, from_email, recipient_list)
        email.attach(attach.name, attach.read(), attach.content_type)
        try:
            email.send(fail_silently=False)
            messages.add_message(request, messages.SUCCESS, 'Document \
                                 Sucessfully Submited For Review!')
            return HttpResponseRedirect('/')
        except SMTPException:
            messages.add_message(request, messages.SUCCESS, 'Failed To Submit Document!')
            return HttpResponseRedirect('/')
    return HttpResponseRedirect('/')

def verify_upload(request):
    '''Adds and Removes database document queue to search index.'''
    if request.method == 'POST':
        idx = Index('indexdir')
        index_queue_file = MEDIA_ROOT + 'temp/index_queue'
        index_remove_file = MEDIA_ROOT + 'temp/remove_queue'

        try:
            if os.path.isfile(index_queue_file):
                idx.create()
                with open(index_queue_file, 'rb') as temp:
                    index_queue = pickle.load(temp)
                for index in index_queue:
                    instance = Document.objects.get(id=index)
                    keyword_tuples = instance.keywords.values_list()

                    temp_keyword_list = many_to_many_field_iter(keyword_tuples)
                    keyword_list = ""
                    for item in temp_keyword_list:
                        keyword_list += item + ','
                    keyword_list = keyword_list[:-1]
                    category_tuples = instance.categories.values_list()
                    temp_category_list = many_to_many_field_iter(category_tuples)
                    category_list = ""
                    for item in temp_category_list:
                        category_list += item + ','
                    category_list = category_list[:-1]
                    file_path = MEDIA_ROOT + str(instance.file)
                    file_url = MEDIA_URL + str(instance.file)
                    img_path = MEDIA_ROOT + "temp/img/"
                    txt_path = MEDIA_ROOT + "temp/txt/"
                    converter = Converter(file_path, img_path, txt_path)
                    content = converter.convert()
                    idx.add(doc_id=str(index),
                            title=instance.title.lower(),
                            url=file_url,
                            content=content.lower(),
                            author=instance.author.lower(),
                            publication=instance.publication.lower(),
                            pub_date=instance.publication_date.lower(),
                            keyword=keyword_list.lower(),
                            category=category_list.lower())

                os.remove(index_queue_file)
                messages.add_message(request, messages.SUCCESS, 'File Sucessfully Added!')
            else:
                messages.add_message(request, messages.WARNING, 'No files to add.')
        except IOError:

            err = sys.exc_info()[0]

            messages.add_message(request, messages.ERROR, "Error: %s" % err)
            messages.add_message(request, messages.ERROR, "Error:1 %s" % err)
            messages.add_message(request, messages.ERROR, 'Sync Failed!')
            return HttpResponseRedirect('/admin/')

        try:
            if os.path.isfile(index_remove_file):
                idx.create()
                with open(index_remove_file, 'rb') as remove_temp:
                    remove_queue = pickle.load(remove_temp)

                for index in remove_queue:
                    idx.delete('doc_id', str(index))

                os.remove(index_remove_file)
                messages.add_message(request, messages.SUCCESS, 'Files Sucessfully Removed!')
            else:
                messages.add_message(request, messages.WARNING, 'No files to remove.')
        except IOError:
            err = sys.exc_info()[0]
            messages.add_message(request, messages.ERROR, "Error:2 %s" % err)

            messages.add_message(request, messages.ERROR, 'Sync Failed!')
            return HttpResponseRedirect('/admin/')

        return HttpResponseRedirect('/admin/')

    return HttpResponseRedirect('/admin/')


def many_to_many_field_iter(tuple_list):

archive/templates/archive/base.html
{% load staticfiles %}
{% spaceless %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, width=device-width, height=device-height, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>{% block title %}RSVP America{% endblock %}</title>
    {% block conditional-css %}{% endblock %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:300,400,700' rel='stylesheet' type='text/css'>
    <link href="{% static 'fpp_archive/dist/css/style.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="{% static 'fpp_archive/img/logo/favicon.ico' %}" />
    <link rel="apple-touch-icon-precomposed" href="{% static 'fpp_archive/img/logo/ios_bookmark.png' %}"/>
  </head>
  <body>
    <header itemscope itemtype="https://schema.org/WebSite">
      {% if messages %}
        {% for message in messages %}
          {% if message.tags == 'success' %}
          <p class="status-message success"><i class="fa fa-times-circle"></i>{{ message }}</p>
          {% elif message.tags == 'error' %}
          <p class="status-message failure"><i class="fa fa-times-circle"></i>{{ message }}</p>
          {% endif %}
        {% endfor %}
      {% endif %}
      <nav class="menu site-width plain-link-light title-font">
        <ul id="menu">
          <li><a href="/"><i class="fa fa-home"></i></a></li>
          <li><a href="/mission">Our Mission</a></li>
          <li><a href="/history">About RSVP America</a></li>
          <li><a href="/categories">Online Archive</a></li>
          <!--<li><a href="#">Key Documents</a></li>-->
          <li><a href="/articles">Articles</a></li>
          <li><a href="/media">Media</a></li>
          <li><a href="http://shop.rsvpamerica.org/">Store</a></li>
        </ul>
      </nav>
    </header>

    {% block pre-search %}{% endblock %}

    {% block search %}
    <section class="intro site-width">
      <h1>RSVP America Campaign</h1>
      <p class="narrow-site-width">RSVP America began in 1994 as a grassroots movement to restore legal protection - state by state - for marriage, women, and children.</p>
      <hr>
    </section>
    <div class="search" itemscope itemtype="https://schema.org/WebSite">
      <form class="site-width" itemprop="potentialAction" itemscope itemtype="https://schema.org/SearchAction" action="{% url 'archive:results' %}" method="get">
        <div>
          <i class="fa fa-search fa-2x"></i><input itemprop="query-input" type='search' class="search-box" name='q' placeholder="Search for keyword" />
          <button type="submit"><i class="fa fa-search fa-2x"></i></button>
        </div>
        <div class="advanced-search">
          <input type="checkbox" name="fulltext" title="Enable slower full text search. This will show more results." />
          <span title="Enable slower full text search. This will show more results.">Full Text Search</span>
        </div>
      </form>
    </div>
    {% endblock %}

    {% block content %}{% endblock %}
    <footer>
      <section class="summary site-width">
        <h2 class="text-center">RSVP America</h4>
        <p>For over 15 years RSVP America has campaigned to reverse
          this deconstruction and to rebuild our societal foundation of
          virtue and purity. This website marks the next chapter for
          RSVP America, particularly for the next generation. Featuring
          our work to restore social virtue and purity to America, this
          website contains vital resources and information that are
          critical in continuing our mission. We welcome your support
          and participation in restoring our marriage, families, towns,
          and nation for a better tomorrow.</p>
      </section>
      <section class="copyright">
        <div class="site-width" itemscope itemtype="https://schema.org/WebSite">
          <span itemprop="copyrightYear">Copyright &copy; {% now "Y" %}</span>
          <span itemprop="copyrightHolder">RSVP America</span>
          <span>All Rights Reserved</span>
          <span itemprop="creator">Website by <a class="plain-link" href="http://bigideainteractive.com/" alt="Big Idea Interactive Media - Web Development, Creative Services, Internet Marketing, and Brand Development in Louisville, KY" title="Big Idea Interactive Media - Web Development, Creative Services, Internet Marketing, and Brand Development in Louisville, KY" target="_blank" itemscope itemtype="https://schema.org/Organization" itemprop="name">Big Idea Interactive</a></span>
        </div>
      </section>
    </footer>
    <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.min.js"></script>
    <script src="{% static 'fpp_archive/js/jquery.slicknav.min.js' %}"></script>
    <script>
      // Picture element HTML5 shiv
      document.createElement( "picture"  );
    </script>
    <script src="{% static 'fpp_archive/js/picturefill.min.js' %}" async></script>
    {% block conditional-js %}{% endblock %}
    <script>
      $(function(){
        $('#menu').slicknav();
      });
    </script>
    {% if messages %}
      {% for message in messages %}
        {% if message.tags == 'success' %}
        <script>
          $("p.status-message .fa").click(function(){
            $("p.status-message").addClass("hidden");
          });
        </script>
        {% elif message.tags == 'error' %}
        <script>
          $("p.status-message .fa").click(function(){
            $("p.status-message").addClass("hidden");
          });
        </script>
        {% endif %}
      {% endfor %}
    {% endif %}
  </body>
</html>
{% endspaceless %}

archive/templates/archive/categories.html
{% extends "archive/base.html" %}
{% load staticfiles %}
{% load fpp_extras %}

{% block title %}FPP Archive &ndash; Categories{% endblock %}

{% block conditional-css %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
{% endblock %}

{% block pre-search %}
{% endblock %}

{% block content %}
<div id="accordion-wrap" class="site-width">
  <p class="instruction">Access our online archive of important historical documents by entering
    search terms in the search field above, or by browsing the categories
    below.</p>
  <section class="categories-content">
    <h1 class="text-center">Categories</h1>
    <div class="site-width main-category">
      <ul>
        <li><a href='/results/?cat="Protecting+Women+and+Children"'>Protecting Women and Children</a></li>
        <li><a href='/results/?cat="Social+Virtue+and+Public+Policy"'>Social Virtue and Public Policy</h3></li>
        <li><a href='/results/?cat="Health+and+Wellness"'>Health and Wellness</a></li>
        <li><a href='/results/?cat="Procreation+Fertility+and+Eugenics"'>Procreation, Fertility and Eugenics</a></li>
        <li><a href='/results/?cat="Virtue+in+the+Military"'>Virtue in the Military</a></li>
      </ul>
    </div>
  </section>
</div>
{% endblock %}

archive/templates/archive/history.html
{% extends "archive/base.html" %}
{% load staticfiles %}
{% load fpp_extras %}

{% block title %}History &ndash; RSVP America{% endblock %}

{% block content %}
<div class="site-width">
  <section class="body-copy">
    <h1>A Brief History</h1>
    <p>The RSVP America Campaign calls attention to the root cause of the
      rising levels of moral decline in America today. In the 1940s,
      zoologist Dr. Alfred Kinsey turned his research away from studying gall
      wasps to focus on human sexual behavior, culminating in the 1948
      publication of Sexual Behavior and the Human Male. With this volume and
      its successors, Kinsey became the go-to authority for the “science” of
      sex, and is largely credited with triggering the Sexual Revolution.
      Despite his widespread influence and authority, the basis for Kinsey’s
      research was “junk science.” Kinsey conducted his research using men in
      respected white coats who fraudulently gathered data by soliciting,
      interviewing, and observing participants in every imaginable sort of
      sexual couplings. A Former Director of the Kinsey Institute later
      admitted that those respectable researchers were no less than male
      homosexual child molesters. The scientific moorings of America’s now
      prevailing sexual pedagogy and law order, developed initially by a gall
      wasp specialist, can be shown to be built upon fraud and brutal,
      criminal child abuse.</p>
    <p>Although Kinsey’s research had been debunked, the results of his
      findings had long-lasting and overarching effects. Laws had been
      changed in nearly every state, eliminating protections for women and
      children across the nation. Such vast changes to the law were made
      possible by the American Law Institute’s Model Penal Code, using
      Kinsey’s data to implement widespread policy reform. The Model Penal
      Code was instrumental in the deconstruction of law, medicine,
      education, the Church, and the military, thereby affecting the overall
      moral fortitude of all other fields within our society.</p>
    <p>For over 15 years, RSVP America has campaigned to reverse this
      deconstruction and to rebuild our societal foundation of virtue and
      purity. This website marks the next chapter for RSVP America,
      particularly for the next generation. Featuring our work to restore
      social virtue and purity to America, this website contains vital
      resources and information that are critical in continuing our mission.
      We welcome your support and participation in restoring our marriages,
      families, towns, and nation for a better tomorrow.</p>
  </section>
  <hr>
  <section class="body-copy">
    <h1>A Report from Eunice V. Ray, Founder</h1>
    <p>The RSVP America Campaign officially began as a ladies’ march on the
      steps of the Capitol in Washington, D.C., in 1997, after 3 years of
      previous planning. The campaign was ignited by Robert Knight’s Family
      Research Council 1994 documentary, “The Children of Table 34.” Bob’s
      video story detailed Dr. Kinsey’s collaboration with “trained observers”
      who engaged in “sexual experimentation” on babies and children, which he
      called “scientific” research into human sexuality in his first volume.
      The Family Research video took its title from the actual “Table 34,” on
      page 181 of Kinsey’s Sexual Behavior in the Human Male, his first volume
      of sex research published in 1948.</p>
    <p>RSVP America formed a ladies’ campaign to warning parents of Kinsey’s
      destructive ongoing legacy for children today and enlisted the help of
      Concerned Women for America (CWA), where I spoke to their National
      Leadership Conference in Dallas, Texas during the spring of 1997.</p>
    <p>To guide parents, we published the RSVP America Parents’ Training Manual
      and distributed it nationally. We went to national and state leaders in
      Government, Education, Medicine, the Church and Law and briefed them on
      the pervasive Kinseyan “junk science” in their fields and a 1953-54
      Congressional Committee’s finding that:</p>
    <blockquote>
      <p>…the Foundation sponsored Kinsey Reports were deliberately designed
      as an attack on Judaic-Christian morality.</p>
      <span class="attribution">Rene Wormser, The Foundations: Their Power and
        Influence (1957)</span>
    </blockquote>
    <p>In December of 1995, with 48 co-sponsors in the US House of
      Representatives, RSVP America led women from across the country to
      Washington, D.C., and called for an investigation into The Kinsey Reports
      destructive impact on women and children.</p>
    <p>Astonishingly, the mere announcement of a Congressional inquiry into
      Kinsey received a world-wide media response because the fraudulent
      Kinseyan sexuality model is THE World’s view of human sexuality.</p>
    <p>Coincidentally to the work in Washington, RSVP America also briefed state
      legislators in all 50 states on how The Kinsey Reports were the
      scientific authority use to degrade once protective American criminal
      laws in favor of predators and generally permit a “Sexual Revolution” in
      all of America’s institutions beginning in the 1960s, which became known
      as a time of “sex, drugs and rock n’ roll.”</p>
    <p>The research undertaken by RSVP America needs to be made available online
      and in physical form. Today, the collection represents an extensive
      archive of historical books, materials, news accounts, published papers,
      including government records from 37 states. There are essays, White
      Papers, books, national media reports, video clips and other documents
      published over the years for a variety of audiences. A partial list is
      attached here at the end of this letter.</p>
    <p>Over the next two years, the work of the RSVP America Campaign (which was
      to mark the 50th anniversary of The Kinsey Reports and assess its impact
      upon our national life), needs to be summarized and archived by subject
      matter on just how Kinsey’s junk science was used to corrupt Law,
      Education, and Medicine in America and across the World.</p>
    <p>The publication of this summary along with the many other RSVP America
      publications and the important and wide ranging archive collected over
      nearly 20 years needs to be made available online. We would also like to
      print and distribute the summary of law changes and an annotated
      bibliography, if funds are available. The collection and archive, online
      giving, and worldwide access to publications need to be accomplished now,
      while those who conducted the research and the RSVP America Campaign,
      (like the invaluable and irreplaceable Dr. Linda Jeffrey), are still
      available and active.</p>
    <p>This project is necessary to memorialize hard won research findings,
      authorities, and information for those worldwide who are working today
      and will come after us. Not only was America deceived, but also the Third
      World as well who suffer under the corrupting Kinsey “culture of death”
      frauds posing as science. We have researched the questions and the
      answers for those across the World who are willing to stand in the
      breach, as we have done over the last nearly 20 years. The RSVP America
      Campaign summary and archive of well documented essays defines the
      problem and then we make concrete suggestions for solutions.</p>
    <p>Finally, despite The Kinsey Reports’ intention to focus on sexual
      mechanics and perversions, the most damaging impact was using The Kinsey
      Reports to change and abolish American common laws to permit and “point
      the way” to such abuses. The national mass media of the mid twentieth
      century favorably reviewed and promoted The Kinsey Reports and major Law
      Review publications called for widespread “science-based legal reform” in
      every state to abolish the “archaic” common law Christian principles at
      the foundation of each state’s criminal code.</p>
    <p>RSVP America intends to make it possible, for those whose heart is
      tender, to restore God’s law and make it honorable again (Isaiah 42) in
      America, to find the Truth about this matter; to find support; and
      encouragement in the fight via the body of historic information God has
      revealed to us. Then the World, because of America’s God given leadership
      position in the World, will receive Godly leadership exported from
      America instead of the large import of Kinsey’s corruption sent from
      American shores. We appreciate your prayerful support.</p>
    <span class="attribution">Eunice Van Winkle Ray,<br>RSVP America Founder
      &amp; National Coordinator</span>
  </section>
</div>
{% endblock %}

archive/templates/archive/search_results.html
{% extends "archive/base.html" %}
{% load staticfiles %}
{% load fpp_extras %}

{% block pre-search %}<div class="search-results-banner"></div>{% endblock %}

{% block content %}
<section itemscope itemtype="https://schema.org/SearchResultPage" class="search-results site-width">
    <span>Search For: </span><h2>{{ query }}</h2>
    <p>Showing {{ first_doc }}-{{ last_doc }} of {{ total }} Documents</p>
    <hr class="separator">
    <ul>
        {% for result in results %}
        <li>
            <h3><a class="plain-link" href="{{ result.url }}" alt="{{ result.title }}">{{ result.title|title }}</a></h3>
            <dl>
                {% if result.author %}
                <span>
                  <dt>Author:</dt>
                  <dd  itemprop="author">{{ result.author|title }}</dd>
                </span>
                {% endif %}
                {% if result.publication %}
                <span>
                  <dt>Publication:</dt>
                  <dd itemprop="citation">{{ result.publication|title }}</dd>
                </span>
                {% endif %}
                {% if result.category %}
                <span>
                  <dt>Category:</dt>
                  <dd itemprop="citation">{{ result.category }}</dd>
                </span>
                {% endif %}
            </dl>
            {% if result.keyword %}
            <dl class="keywords">
                <dt>Keywords:</dt>
                <dd>{{ result.keyword|keylist:','|safe }}</dd>
            </dl>
            {% endif %}
            <hr class="separator">
        </li>
        {% endfor %}
    </ul>
</section>


<div class="pagination site-width">
  {% if results.has_previous %}
  <a class="plain-link previous-page" href="{% url 'archive:results' %}?{% if query %}q={{ query  }}{% endif %}{% if cat %}cat={{ cat  }}{% endif %}&page={{ results.previous_page_number  }}{% if full_text %}&fulltext=on{% endif %}"><i class="fa fa-arrow-left"></i> Previous</a>
  {% endif %}

  {% if total > 12 %}
  <ul>
    {% for page in page_range %}
    <li><a class="plain-link" href="{% url 'archive:results' %}?{% if query %}q={{ query  }}{% endif %}{% if cat %}cat={{ cat  }}{% endif %}&page={{ page  }}{% if full_text %}&fulltext=on{% endif %}">{{ page  }}</a></li>
    {% endfor %}
  </ul>
  {% endif %}

  {% if results.has_next %}
  <a class="plain-link next-page" href="{% url 'archive:results' %}?{% if query %}q={{ query  }}{% endif %}{% if cat %}cat={{ cat  }}{% endif %}&page={{ results.next_page_number  }}{% if full_text %}&fulltext=on{% endif %}">Next <i class="fa fa-arrow-right"></i></a>
  {% endif %}
</div>

{% endblock %}